name: fund_dbt_project
version: 1.0.0
profile: fund_dbt

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

models:
  staging:
    # Drop the existing table and create a new one
    +materialized: table
    +schema: staging
  marts:
    # Incrementally update the table
    +materialized: incremental

    fund:         # <= Match the folder: models/marts/fund
      +schema: bi # <= Match the schema.